version: "3"
services: 
  mongo:
    container_name: mongo-container 
    image: mongo:5.0.3
    restart: always
    volumes:
      - ./data:/data/db
    ports: 
      - "27019:27017"
  api:
    container_name: api-container
    image: node:16.13
    working_dir: /var/www/liven
    restart: always
    command: bash -c "npm install -g inherits && npm install --only=production --force && npm run debug"
    volumes: 
      - ./dist/:/var/www/liven/dist/
      - ./package.json:/var/www/liven/package.json

    ports: 
      - "3000:3000"
      - "9222:9222"
    links:
      - mongo